name: mi_thermo_reader
description: "An app for reading thermometer values of Mi Thermometer flashed with custom Firmware from https://github.com/pvvx/ATC_MiThermometer."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.3+10

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^2.0.1
  proto_annotations: ^6.0.0
  protobuf: ^6.0.0
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  fl_chart: ^1.0.0
  intl: ^0.20.2
  fixnum: ^1.1.1 # For generated proto code.
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  stats: ^3.0.0
  collection: ^1.19.1
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  in_app_review: ^2.0.11
  region_settings: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.0
  custom_lint:
  flutter_launcher_icons: "^0.14.4"
  # TODO(panmari: Reintroduce proto_generator when it works again.)
  # proto_generator: ^7.0.4
  mockito: ^5.6.3
  shared_preferences_platform_interface: ^2.4.1
  flutter_blue_plus_platform_interface: ^8.1.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
